name: build pkg CI

on: [workflow_dispatch]
  
jobs:
  build_pkg:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        openwrt_sdk_version: [21.02.0-rc4]
    steps:
      - name: Check out nic-persist-naming repo
      - uses: actions/checkout@v2
        with:
          path: ./nic-persist-naming
